FROM alpine:3.10

RUN apk add --no-cache python3-dev \
&& pip3 install --upgrade pip

WORKDIR /app

COPY . /app


RUN apk add --update --no-cache --virtual .tmp-build-deps \
    gcc libc-dev linux-headers postgresql-dev \
    && apk add libffi-dev

RUN pip3 --no-cache-dir install -r requirements.txt

CMD ["python3", "app.py"]

EXPOSE 5500


